
@echo off
cd /d "%~dp0"
echo Starting IR News Scraper...
echo Installing dependencies (if needed)...
python -m pip install -r requirements.txt > nul
echo Launching Streamlit App...
streamlit run streamlit_app.py
pause
